# Generated by Django 5.2.7 on 2025-10-16 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部署名')),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.dept', verbose_name='所属部署')),
            ],
        ),
    ]
