# Generated by Django 5.2.7 on 2025-10-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='試験名')),
                ('date', models.DateField(verbose_name='実施日')),
            ],
            options={
                'verbose_name': '試験',
                'verbose_name_plural': '試験',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学生名')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='点数')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.exam', verbose_name='試験')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成績',
                'verbose_name_plural': '成績',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
